[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.build]
cmds = [
  "pip install -r requirements.txt",
  "wget https://huggingface.co/ezioruan/inswapper_128.onnx/resolve/main/inswapper_128.onnx -O inswapper_128.onnx"
]

[start]
cmd = "gunicorn app:app"
