[phases.setup]
nixPkgs = ["python311", "gcc", "curl"]

[phases.build]
cmds = [
  "pip install -r requirements.txt",
  "curl -L https://huggingface.co/ezioruan/inswapper_128.onnx/resolve/main/inswapper_128.onnx -o inswapper_128.onnx"
]

[start]
cmd = "gunicorn app:app"
