services:
  - type: web
    name: faceswap-insightface
    runtime: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      wget https://huggingface.co/deepinsight/inswapper/resolve/main/inswapper_128.onnx -O inswapper_128.onnx
    startCommand: gunicorn app:app
