services:
  - type: web
    name: facefusion-server
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: REPLICATE_API_TOKEN
        value: TU_TOKEN_PRIVADO
